# Generated by Django 5.2.1 on 2025-05-23 13:37

import django.db.models.deletion
from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_salon', '0001_initial'),
        ('car_brand', '0001_initial'),
        ('car_model', '0003_alter_carmodelmodel_car_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSalonListingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.services.file_service.upload_listing_photo)),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'UER'), ('UAH', 'UAH')], default='USD', max_length=3)),
                ('price_usd', models.FloatField(blank=True, null=True)),
                ('price_eur', models.FloatField(blank=True, null=True)),
                ('price_uah', models.FloatField(blank=True, null=True)),
                ('exchange_rate_used', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('avg_city_price', models.FloatField(blank=True, null=True)),
                ('avg_region_price', models.FloatField(blank=True, null=True)),
                ('avg_country_price', models.FloatField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('daily_views', models.IntegerField(default=0)),
                ('weekly_views', models.IntegerField(default=0)),
                ('monthly_views', models.IntegerField(default=0)),
                ('last_view_date', models.DateField(blank=True, null=True)),
                ('bad_word_attempts', models.IntegerField(default=0)),
                ('auto_salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_salon_listings', to='auto_salon.autosalonmodel')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_salon_listings', to='car_brand.carbrandmodel')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_salon_listings', to='car_model.carmodelmodel')),
            ],
            options={
                'db_table': 'auto_salon_listings',
            },
        ),
    ]
