# Generated by Django 5.2.1 on 2025-05-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_salon_listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosalonlistingmodel',
            name='last_view_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
