# Generated by Django 5.2 on 2025-05-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listingsellersmodel_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingsellersmodel',
            old_name='model_name',
            new_name='car_model',
        ),
    ]
