# Generated by Django 5.2.1 on 2025-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_model_name_listingsellersmodel_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsellersmodel',
            name='description',
            field=models.CharField(default='No description', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingsellersmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
