# Generated by Django 5.2.1 on 2025-05-12 09:42

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listingsellersmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingsellersmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.upload_listing_photo),
        ),
    ]
