# Generated by Django 5.2.1 on 2025-05-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listingsellersmodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsellersmodel',
            name='avg_city_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingsellersmodel',
            name='avg_country_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingsellersmodel',
            name='avg_region_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
