# Generated by Django 5.2.1 on 2025-05-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listingsellersmodel_avg_city_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingsellersmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='listingsellersmodel',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='listingsellersmodel',
            name='exchange_rate_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listingsellersmodel',
            name='price_eur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingsellersmodel',
            name='price_uah',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingsellersmodel',
            name='price_usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
