# Generated by Django 5.2.1 on 2025-05-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_listingsellersmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsellersmodel',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
