# Generated by Django 5.2.1 on 2025-05-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listingsellersmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsellersmodel',
            name='bad_word_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingsellersmodel',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
