# Generated by Django 5.2.1 on 2025-05-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listingsellersmodel_bad_word_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingsellersmodel',
            name='is_blocked',
        ),
    ]
