# Generated by Django 5.2.1 on 2025-05-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_listingsellersmodel_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingsellersmodel',
            name='last_view_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
