# Generated by Django 5.2 on 2025-05-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodelmodel',
            old_name='model_name',
            new_name='car_model',
        ),
    ]
