# Generated by Django 5.2 on 2025-05-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_sellersmodel_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellersmodel',
            name='listings',
        ),
    ]
