# Generated by Django 5.2 on 2025-05-05 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_remove_sellersmodel_listings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellersmodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='sellersmodel',
            name='male',
        ),
        migrations.RemoveField(
            model_name='sellersmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sellersmodel',
            name='surname',
        ),
        migrations.AddField(
            model_name='sellersmodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
