# Generated by Django 5.2 on 2025-05-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_remove_sellersmodel_age_remove_sellersmodel_male_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
