# Generated by Django 5.2 on 2025-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_sellersmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersmodel',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
