# Generated by Django 5.2 on 2025-05-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_sellersmodel_total_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellersmodel',
            name='total_views',
        ),
    ]
