# Generated by Django 5.2.1 on 2025-05-21 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_to_auto_salon', '0002_alter_joinrequestmodel_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequestmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
