# Generated by Django 5.2 on 2025-05-04 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0004_alter_listingsellersmodel_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewListingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.IntegerField(default=0)),
                ('listings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='listings.listingsellersmodel')),
            ],
            options={
                'db_table': 'view_listing',
            },
        ),
    ]
