# Generated by Django 5.2 on 2025-05-04 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewlistingmodel',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
