# Generated by Django 5.2 on 2025-05-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_listing', '0002_viewlistingmodel_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewlistingmodel',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='viewlistingmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
