# Generated by Django 5.2 on 2025-05-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_listing', '0003_rename_timestamp_viewlistingmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewlistingmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
