# Generated by Django 5.2 on 2025-05-04 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listingsellersmodel_seller'),
        ('view_listing', '0004_alter_viewlistingmodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewlistingmodel',
            name='listings',
        ),
        migrations.AddField(
            model_name='viewlistingmodel',
            name='listings_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='view_listing', to='listings.listingsellersmodel'),
            preserve_default=False,
        ),
    ]
