# Generated by Django 5.2 on 2025-05-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_listing', '0005_remove_viewlistingmodel_listings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewlistingmodel',
            old_name='listings_id',
            new_name='listings',
        ),
    ]
