# Generated by Django 5.2 on 2025-05-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_listing', '0006_rename_listings_id_viewlistingmodel_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewlistingmodel',
            name='view',
        ),
    ]
