# Generated by Django 5.2 on 2025-05-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_listing', '0007_remove_viewlistingmodel_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewlistingmodel',
            name='view',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
