# Generated by Django 5.2 on 2025-05-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0006_sellersmodel_total_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(default='premium', max_length=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_account', to='sellers.sellersmodel')),
            ],
            options={
                'db_table': 'premium_account',
            },
        ),
    ]
