# Generated by Django 5.2 on 2025-05-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumaccountmodel',
            name='purchased_at',
        ),
    ]
