# Generated by Django 5.2 on 2025-05-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingSellersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'listings',
            },
        ),
    ]
