# Generated by Django 5.2 on 2025-05-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('sellers', '0003_remove_sellersmodel_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsellersmodel',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sellers.sellersmodel'),
            preserve_default=False,
        ),
    ]
