# Generated by Django 5.2 on 2025-05-03 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingsellersmodel_seller'),
        ('sellers', '0003_remove_sellersmodel_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingsellersmodel',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listingsellersmodel',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listingsellersmodel',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listingsellersmodel',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listingsellersmodel',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listingsellersmodel',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='sellers.sellersmodel'),
        ),
    ]
