# Generated by Django 5.2 on 2025-05-03 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listingsellersmodel_brand_and_more'),
        ('sellers', '0003_remove_sellersmodel_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingsellersmodel',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='sellers.sellersmodel'),
        ),
    ]
