# Generated by Django 5.2 on 2025-05-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listingsellersmodel_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsellersmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
