# Generated by Django 5.2 on 2025-05-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listingsellersmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsellersmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
