# Generated by Django 5.2 on 2025-05-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listingsellersmodel_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingsellersmodel',
            name='views',
        ),
    ]
