# Generated by Django 5.2 on 2025-05-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listingsellersmodel_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsellersmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
