# Generated by Django 5.2 on 2025-05-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listingsellersmodel_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsellersmodel',
            name='daily_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingsellersmodel',
            name='last_view_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingsellersmodel',
            name='monthly_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingsellersmodel',
            name='weekly_views',
            field=models.IntegerField(default=0),
        ),
    ]
