# Generated by Django 5.2 on 2025-05-09 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=100)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='car_brand.carbrandmodel')),
            ],
            options={
                'db_table': 'car_model',
            },
        ),
    ]
