# Generated by Django 5.2 on 2025-05-09 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_brand', '0001_initial'),
        ('car_model', '0002_rename_model_name_carmodelmodel_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodelmodel',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='car_brand.carbrandmodel'),
        ),
    ]
