# Generated by Django 5.2.1 on 2025-05-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_salon', '0001_initial'),
        ('premium_account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumaccountmodel',
            name='auto_salon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_account', to='auto_salon.autosalonmodel'),
        ),
    ]
