# Generated by Django 5.2.1 on 2025-05-23 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_account', '0003_premiumaccountmodel_auto_salon'),
        ('sellers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumaccountmodel',
            name='seller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_account', to='sellers.sellersmodel'),
        ),
    ]
