# Generated by Django 5.2.1 on 2025-05-29 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,29}$', 'Only alpha characters are allowed!')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='country',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,29}$', 'Only alpha characters are allowed!')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,9}$', 'Only alpha characters are allowed!')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,19}$', 'Only alpha characters are allowed!')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='region',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,29}$', 'Only alpha characters are allowed!')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='street',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,29}$', 'Only alpha characters are allowed!')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,19}$', 'Only alpha characters are allowed!')]),
        ),
    ]
