# Generated by Django 5.2.1 on 2025-05-21 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_salon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonRoleModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('seller', 'Seller'), ('mechanic', 'Mechanic')], max_length=10)),
                ('auto_salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_role', to='auto_salon.autosalonmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salon_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auto_salon_role',
            },
        ),
    ]
