# Generated by Django 5.2.1 on 2025-05-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_salon', '0001_initial'),
        ('salon_role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonrolemodels',
            name='auto_salon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salon_role', to='auto_salon.autosalonmodel'),
        ),
    ]
